# Generated by Django 5.2.12 on 2026-03-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='trained_at',
            field=models.CharField(blank=True, max_length=100, verbose_name='Training Institute'),
        ),
    ]