# Generated by Django 5.2.12 on 2026-03-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, help_text='Enter specific rules or guidelines for this exam.', null=True),
        ),
    ]
